[package]
name = "d01"
version = "0.1.0"
authors = ["Kristjan Siimson <k.siimson@sportradar.com>"]
edition = "2018"

[dependencies]
btoi = "0.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main"
harness = false
