[package]
name = "d07"
version = "0.1.0"
authors = ["Kristjan Siimson <k.siimson@sportradar.com>"]
edition = "2018"

[dependencies]
nom = "6"
ustr = "0.7.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main"
harness = false
